apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: q0n8xtc6z-dotnet-basic
  janus-idp.io/tekton: q0n8xtc6z-dotnet-basic
  backstage.io/kubernetes-id: q0n8xtc6z-dotnet-basic
  backstage.io/kubernetes-namespace: tssc-app 
  app.kubernetes.io/part-of: q0n8xtc6z-dotnet-basic
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
